<a href="https://colab.research.google.com/github/gsimeon/AI-For-Beginners/blob/main/Assignment_Arewa_kesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.5.1+cu121'

In [ ]:
# Create a random tensor of size (7, 7)
Y = torch.rand(size=(7, 7))
Y, Y.dtype

(tensor([[0.9191, 0.9220, 0.0034, 0.4932, 0.8817, 0.2728, 0.4311],
         [0.5025, 0.1436, 0.5941, 0.5051, 0.5268, 0.1800, 0.9810],
         [0.2647, 0.8458, 0.9199, 0.7094, 0.6582, 0.9288, 0.6968],
         [0.5114, 0.4495, 0.9788, 0.9098, 0.1476, 0.1783, 0.1199],
         [0.9974, 0.3922, 0.9110, 0.1106, 0.7318, 0.5124, 0.9822],
         [0.3627, 0.9858, 0.3355, 0.8780, 0.5994, 0.6710, 0.6351],
         [0.8928, 0.0192, 0.6613, 0.8836, 0.0164, 0.0172, 0.7352]]),
 torch.float32)

In [ ]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
Y = torch.rand(size=(7, 7))
Z = torch.rand(size=(1, 7))
Y, Z
X = torch.matmul(Y, Z.T)
X, X.shape
#

(tensor([[2.0872],
         [2.4793],
         [1.2806],
         [2.0890],
         [1.9042],
         [2.4884],
         [1.0742]]),
 torch.Size([7, 1]))

In [ ]:
#Set the random seed to 0 and do 2 & 3 over again
import torch
torch.manual_seed(0)
Y = torch.rand(size=(7, 7))
Z = torch.rand(size=(1, 7))
Y, Z
X = torch.matmul(Y, Z.T)
X, X.shape
#

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [2]:
import torch

2. Create a random tensor with shape (7, 7).**


In [3]:
# Create a random tensor with shape (7, 7)
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.8821, 0.6947, 0.0121, 0.5378, 0.3031, 0.3743, 0.7720],
         [0.1825, 0.5919, 0.4320, 0.3706, 0.7459, 0.0158, 0.8811],
         [0.3602, 0.5230, 0.7228, 0.8082, 0.6798, 0.7125, 0.2525],
         [0.2539, 0.8123, 0.5865, 0.4701, 0.2704, 0.6263, 0.4433],
         [0.7361, 0.5087, 0.7734, 0.6699, 0.9080, 0.1571, 0.3366],
         [0.2283, 0.9190, 0.8339, 0.3973, 0.7508, 0.2352, 0.6268],
         [0.2422, 0.6756, 0.7258, 0.1793, 0.0615, 0.9089, 0.6789]]),
 torch.Size([7, 7]))

**3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).**

In [4]:
# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
Y = torch.rand(size=(1, 7))
X = torch.matmul(X, Y.T)
X, X.shape


(tensor([[0.9460],
         [0.9780],
         [1.1611],
         [0.8968],
         [1.0437],
         [1.0310],
         [0.9494]]),
 torch.Size([7, 1]))

**Set the random seed to 0 and do 2 & 3 over again**

In [5]:
# Set the random seed to 0 and do 2 & 3 over again
torch.manual_seed(0)
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))
X = torch.matmul(X, Y.T)
X, X.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

**Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)**

In [10]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
torch.cuda.is_available()
!nvidia-smi
# set the GPU random seed to 1234
torch.cuda.manual_seed(1234)


/bin/bash: line 1: nvidia-smi: command not found


**Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:**

In [8]:
# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
# The output should be something like:
torch.manual_seed(1234)
X = torch.rand(size=(2, 3)).to("cuda")
Y = torch.rand(size=(2, 3)).to("cuda")
X, Y

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx